sudo: false
language: ruby
cache: bundler
rvm:
- 2.5
- 2.6
before_install: rm -f Gemfile.lock
script: bundle exec rake test
notifications:
  slack:
    rooms:
      secure: TgsONpckMP+cKPvC0+obx96NqmU63iWUtYC03Qpagtwc5ToIQgiVQ+ZSUQShPhMcxApQ4SvVy2NuFN+hrivFd9jZfNe7FHW9/7EMF2j7VMYP235CMPJjw0FnwwEzqU+VTtoffCZVfJjkDdgV02I/D5UOsf2A0X0iS0T8QlIhUUahBE9UADqMyRGoqZMjayascFM5ckBzNdcZ36TkEDppEqFub8/dv/VYgxX+WddcYBbSPuNBy3I/sGCSYw7aQ6JZ/fnd94sxmiw3f2Xe9bLaRioFJOG/8vEjoZOODE0f276Tx9z9HQIhCQq0nmlAKXN+HTcluZsbbp22Q9JhfXGQ3IgOo9axB/PUgJJyiqZcHleJLyVrfyl0vbKxYvOX8NX5Gb2eYnKyucjuWUL0ljkmVoVENV2kDthUlRpsJasZGcDMwaXbSuEH6hYgl4YifqIbnpdxCJXLwAWwVi5xNfaNM9z+Mk/pZE1W3+OD0Epe21JfFiQMxqvf3o5thVNeBdJAdciuZ6RC0aMQE8JxZQ087uVAS2AENIL7Ww1rMZdXztGXm24Z2Ms845D5ktEJOFOE4CsqoSOe62JRzrJzgMxrnlGzzanV0Kw/Msu74xy0zguSG6s4GQlKU7DBM5q3fUdMoU96JOnYBNR+x22OvCqWhdUUrOwmY0aH5G8SJkRhYD4=
